### PR TITLE
feature: add a colab supported python notebook

### PR DESCRIPTION
**Pull request by krishnanunnir**
### Summary

1. The current python notebook can't be run directly in Colab, since dependencies need to be setup first. I added a new notebook with everything set up for colab.
2. Added a requirements.txt file, for all the dependencies, since there are some version issues.

you can check it out - https://colab.research.google.com/github/krishnanunnir/CrossAttentionControl/blob/main/CrossAttention_Release_Colab.ipynb

### CODE REVIEW

**Comment by bloc97** [comment]
Hi, thanks for the update for Colab users. I think the `!git clone https://github.com/krishnanunnir/CrossAttentionControl` line is unnecessary, as the notebook does not have any dependencies on local files. What do you think?

**Comment by QuoteDev** [comment]
> ### Summary
> 
>     1. The current python notebook can't be run directly in Colab, since dependencies need to be setup first. I added a new notebook with everything set up for colab.
> 
>     2. Added a requirements.txt file, for all the dependencies, since there are some version issues.
> 
> 
> you can check it out - https://colab.research.google.com/github/krishnanunnir/CrossAttentionControl/blob/main/CrossAttention_Release_Colab.ipynb

Running`stablediffusion("A fantasy landscape with a pine forest, trending on artstation", seed=2483964025, width=768)` results in the error`AttributeError: 'int' object has no attribute 'to'`. Any idea how to fix this?

**Comment by bloc97** [comment]
Try downgrading to `diffusers==0.3.0`, they've just updated their library to `0.4.0` today and it seems the architecture changes done to cross-attention layers for improving performance breaks the notebook (which needs to inject extra code into the model). A update is on the way...

**Comment by SpicyMelonYT** [comment]
I am having an issue with this notebook: In the final execution line:
`stablediffusion("A fantasy landscape with a pine forest, trending on artstation", seed=2483964025, width=768)`

I get this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-a62f00768874>](https://localhost:8080/#) in <module>
----> 1 stablediffusion("A fantasy landscape with a pine forest, trending on artstation", seed=2483964025, width=768)

2 frames
[/usr/local/lib/python3.7/dist-packages/diffusers/schedulers/scheduling_lms_discrete.py](https://localhost:8080/#) in add_noise(self, original_samples, noise, timesteps)
    260         sigmas = self.sigmas.to(original_samples.device)
    261         schedule_timesteps = self.timesteps.to(original_samples.device)
--> 262         timesteps = self.timesteps.to(original_samples.device)
    263         if isinstance(timesteps, torch.IntTensor) or isinstance(timesteps, torch.LongTensor):
    264             deprecate(

AttributeError: 'int' object has no attribute 'to'
```

**Comment by bloc97** [comment]
It's the same error as above, try downgrading to `diffusers==0.3.0` for now.

**Comment by SpicyMelonYT** [comment]
I copied the notebook, I have no clue how to downgrade that sorry, Could you help?

**Comment by SpicyMelonYT** [comment]
Oh I had assumed that this notebook file would have had that change already. And yeah it seems to work!

**Comment by bloc97** [comment]
An external colab was added (https://github.com/bloc97/CrossAttentionControl/pull/16), closing due to inactivity.

**Pull request closed without merging**
